const CFG=window.PLANT_V2_CONFIG;let lastStatus=null;let lastLiveAt=0;let telemetry=[];let wateringHistory=[];
function url(path){let u=`${CFG.firebaseBaseUrl}${CFG.deviceRoot}${path}.json`;if(CFG.authToken)u+=`?auth=${encodeURIComponent(CFG.authToken)}`;return u}
async function get(path){const r=await fetch(url(path),{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
async function put(path,data){const r=await fetch(url(path),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmtMin(v){const n=Number(v||0);return n<60?`${n} min`:`${Math.floor(n/60)}h ${n%60}m`}
function toast(msg){const e=document.getElementById('toast');e.textContent=msg;e.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>e.hidden=true,3000)}
function commandId(){return `${Date.now()}-${Math.random().toString(16).slice(2)}`}
async function sendCommand(action,extra={}){const id=commandId();await put('/command',{id,action,...extra,issuedAtEpochMs:Date.now()});toast(`Command sent: ${action.replaceAll('_',' ')}`);return id}
function plantCard(p,i){const m=Math.max(0,Math.min(100,Number(p.moisture)||0));const fault=p.fault?'fault':'good';const watering=p.watering?'Watering':p.soaking?'Soaking':'Idle';return `<article class="plant-card" data-i="${i}">
<div class="plant-top"><div><div class="plant-name">${esc(p.name||`Plant ${i+1}`)}</div><small class="${fault}">${p.fault?'Fault detected':'Sensor healthy'}</small></div><span class="mode">${esc(p.mode||'AUTO')}</span></div>
<div class="moisture">${m}%</div><div class="bar"><div style="width:${m}%"></div></div>
<div class="meta-grid"><div class="meta"><span>Target</span><strong>${esc(p.targetRange||`${p.targetLow}-${p.targetHigh}%`)}</strong></div><div class="meta"><span>State</span><strong>${watering}</strong></div><div class="meta"><span>Raw</span><strong>${esc(p.raw)}</strong></div><div class="meta"><span>Last stop</span><strong>${esc(p.lastStopReason||'None')}</strong></div><div class="meta"><span>Last amount</span><strong>${p.lastDeliveredMl||0} ml</strong></div><div class="meta"><span>Today pump</span><strong>${Math.round((p.dailyPumpMs||0)/1000)} sec</strong></div></div>
<div class="actions"><button onclick="waterNow(${i})" ${p.mode==='DISABLED'?'disabled':''}>Water Now</button><button class="secondary" onclick="setMode(${i},'AUTO')">AUTO</button><button class="secondary" onclick="setMode(${i},'MANUAL')">MANUAL</button><button class="secondary" onclick="setMode(${i},'DISABLED')">Disable</button><button class="secondary" onclick="toggleSettings(${i})">Settings</button>${p.fault?`<button class="warning" onclick="clearFault(${i})">Clear Fault</button>`:''}</div>
<div class="settings" id="settings-${i}"><div class="form-grid"><div class="field"><label>Plant name</label><input id="name-${i}" value="${esc(p.name)}"></div><div class="field"><label>Low %</label><input id="low-${i}" type="number" min="0" max="95" value="${p.targetLow}"></div><div class="field"><label>High %</label><input id="high-${i}" type="number" min="1" max="100" value="${p.targetHigh}"></div><div class="field"><label>Burst seconds</label><input id="burst-${i}" type="number" min="1" max="15" value="${Math.round((p.burstMs||3000)/1000)}"></div><div class="field"><label>Burst ml</label><input id="ml-${i}" type="number" min="10" max="2000" value="${p.burstMl||100}"></div><div class="field"><label>Soak seconds</label><input id="soak-${i}" type="number" min="10" max="1800" value="${p.soakSec||120}"></div><div class="field"><label>Min interval minutes</label><input id="interval-${i}" type="number" min="1" value="${p.minIntervalMin||60}"></div><div class="field"><label>Mode</label><select id="mode-${i}"><option ${p.mode==='AUTO'?'selected':''}>AUTO</option><option ${p.mode==='MANUAL'?'selected':''}>MANUAL</option><option ${p.mode==='DISABLED'?'selected':''}>DISABLED</option></select></div></div><div class="actions"><button onclick="saveSettings(${i})">Save Settings</button><button class="secondary" onclick="calibrate(${i},'dry')">Record Dry</button><button class="secondary" onclick="calibrate(${i},'wet')">Record Wet</button></div></div>
</article>`}
function renderStatus(s){lastStatus=s;lastLiveAt=Date.now();document.getElementById('systemBadge').textContent=s.emergencyStop?'STOPPED':'ONLINE';document.getElementById('systemBadge').className=`badge ${s.emergencyStop?'offline':'online'}`;document.getElementById('systemStatus').textContent=s.emergencyStop?'Emergency Stop':s.systemReady?'Ready':'Starting';document.getElementById('heartbeat').textContent=`Updated ${new Date().toLocaleTimeString()}`;const active=Number(s.activePlantIndex);document.getElementById('activePlant').textContent=active>=0?(s.plants?.[active]?.name||`Plant ${active+1}`):'Pump OFF';document.getElementById('wateringAllowed').textContent=s.wateringAllowed?'Watering allowed':'Safety lock active';document.getElementById('tankStatus').textContent=s.tankSensorEnabled?(s.tankEmpty?'EMPTY':'OK'):'Not installed';document.getElementById('tankHint').textContent=s.tankSensorEnabled?'Float sensor active':'Optional hardware';document.getElementById('flowStatus').textContent=s.flowSensorEnabled?'Enabled':'Not installed';document.getElementById('flowHint').textContent=s.flowSensorEnabled?`${s.flowPulses||0} pulses`:'Time-based fallback';document.getElementById('wifiRssi').textContent=`${s.wifiRssi||0} dBm`;document.getElementById('deviceIp').textContent=s.ip||'--';document.getElementById('resetReason').textContent=s.resetReason||'--';document.getElementById('uptime').textContent=`Uptime ${fmtMin(s.uptimeMin)}`;document.getElementById('emergencyBtn').hidden=!!s.emergencyStop;document.getElementById('resumeBtn').hidden=!s.emergencyStop;document.getElementById('plantsGrid').innerHTML=(s.plants||[]).map(plantCard).join('')||'<div class="empty">No plants found.</div>';renderDiagnostics(s)}
function renderDiagnostics(s){const items=[['Firmware',s.firmware],['Reset reason',s.resetReason],['System ready',s.systemReady?'YES':'NO'],['Watering allowed',s.wateringAllowed?'YES':'NO'],['Emergency stop',s.emergencyStop?'ACTIVE':'No'],['Tank sensor',s.tankSensorEnabled?'Enabled':'Not installed'],['Tank state',s.tankEmpty?'EMPTY':'OK / N/A'],['Flow sensor',s.flowSensorEnabled?'Enabled':'Not installed'],['Wi-Fi RSSI',`${s.wifiRssi||0} dBm`],['Device IP',s.ip],['Uptime',fmtMin(s.uptimeMin)],['Active plant',s.activePlantIndex]];document.getElementById('diagnosticsGrid').innerHTML=items.map(x=>`<div class="diag"><span>${esc(x[0])}</span><strong>${esc(x[1]??'--')}</strong></div>`).join('')}
function renderOffline(){document.getElementById('systemBadge').textContent='OFFLINE';document.getElementById('systemBadge').className='badge offline';document.getElementById('systemStatus').textContent='Offline';document.getElementById('heartbeat').textContent='Waiting for V2 firmware heartbeat'}
window.waterNow=async i=>{const s=prompt('Water for how many seconds?','5');if(s===null)return;const sec=Math.max(1,Math.min(45,Number(s)||5));try{await sendCommand('water_now',{plantIndex:i,durationSec:sec})}catch(e){toast(`Failed: ${e.message}`)}};
window.setMode=async(i,mode)=>{try{await sendCommand('set_mode',{plantIndex:i,mode})}catch(e){toast(`Failed: ${e.message}`)}};
window.clearFault=async i=>{try{await sendCommand('clear_fault',{plantIndex:i})}catch(e){toast(`Failed: ${e.message}`)}};
window.calibrate=async(i,kind)=>{if(!confirm(`Record current sensor reading as ${kind.toUpperCase()} calibration?`))return;try{await sendCommand(`calibrate_${kind}`,{plantIndex:i})}catch(e){toast(`Failed: ${e.message}`)}};
window.toggleSettings=i=>document.getElementById(`settings-${i}`).classList.toggle('open');
window.saveSettings=async i=>{try{const cfg={name:document.getElementById(`name-${i}`).value.trim(),targetLow:Number(document.getElementById(`low-${i}`).value),targetHigh:Number(document.getElementById(`high-${i}`).value),burstMs:Number(document.getElementById(`burst-${i}`).value)*1000,burstMl:Number(document.getElementById(`ml-${i}`).value),soakSec:Number(document.getElementById(`soak-${i}`).value),minIntervalMin:Number(document.getElementById(`interval-${i}`).value),mode:document.getElementById(`mode-${i}`).value};if(cfg.targetHigh<=cfg.targetLow)throw new Error('High threshold must be greater than low threshold');await put(`/config/plants/${i}`,cfg);await put('/config/version',String(Date.now()));toast('Settings saved to controller config')}catch(e){toast(`Failed: ${e.message}`)}};
function rows(obj){return obj&&typeof obj==='object'?Object.values(obj):[]}
async function loadHistory(){try{const [t,h]=await Promise.all([get('/history/telemetry'),get('/history/watering')]);telemetry=rows(t).slice(-48);wateringHistory=rows(h).slice(-30).reverse();renderChart();renderHistory()}catch(e){console.warn(e)}}
function renderHistory(){const el=document.getElementById('history');if(!wateringHistory.length){el.innerHTML='<div class="empty">No watering history yet.</div>';return}el.innerHTML=wateringHistory.map(x=>`<div class="history-item"><strong>${esc(x.plantName||`Plant ${Number(x.plantIndex)+1}`)}</strong><small>${Math.round((x.durationMs||0)/1000)} sec · ${x.deliveredMl||0} ml · ${esc(x.reason||'Completed')} · ${x.moistureStart??'--'}% → ${x.moistureEnd??'--'}%</small></div>`).join('')}
function renderChart(){const el=document.getElementById('chart');if(!telemetry.length){el.innerHTML='<div class="empty">No telemetry yet.</div>';return}const plants=telemetry[telemetry.length-1]?.plants||[];const W=700,H=230,pad=25;let paths='';plants.forEach((_,pi)=>{const pts=telemetry.map((r,idx)=>{const x=pad+(idx/Math.max(1,telemetry.length-1))*(W-pad*2);const m=Number(r.plants?.[pi]?.moisture||0);const y=H-pad-(m/100)*(H-pad*2);return `${x.toFixed(1)},${y.toFixed(1)}`}).join(' ');paths+=`<polyline points="${pts}" fill="none" stroke="hsl(${(pi*67)%360} 55% 42%)" stroke-width="3"/>`});el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><line x1="${pad}" y1="${pad}" x2="${pad}" y2="${H-pad}" stroke="#d1d5db"/><line x1="${pad}" y1="${H-pad}" x2="${W-pad}" y2="${H-pad}" stroke="#d1d5db"/>${paths}</svg><div class="chart-legend">${plants.map((p,i)=>`<span>● ${esc(p.name||`Plant ${i+1}`)}</span>`).join('')}</div>`}
function switchView(id){document.querySelectorAll('.dashboard-view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.menu-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='historyView')loadHistory();}
document.querySelectorAll('.menu-btn').forEach(btn=>btn.addEventListener('click',()=>switchView(btn.dataset.view)));
async function refresh(){try{const s=await get('/status');if(!s)throw new Error('No V2 status yet');renderStatus(s)}catch(e){if(Date.now()-lastLiveAt>(CFG.staleTimeoutSec*1000))renderOffline()}}
document.getElementById('emergencyBtn').onclick=async()=>{if(confirm('Stop pump and close all valves?'))try{await sendCommand('emergency_stop')}catch(e){toast(e.message)}};document.getElementById('resumeBtn').onclick=async()=>{if(confirm('Resume automatic watering?'))try{await sendCommand('resume')}catch(e){toast(e.message)}};
refresh();loadHistory();setInterval(refresh,CFG.refreshMs);setInterval(loadHistory,60000);
