(function(){
  const C=window.PLANT_V3_CONFIG, SESSION_KEY="plantV3CustomerSession", state={session:null,loading:false};
  const el=id=>document.getElementById(id);
  const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]));
  const query=new URLSearchParams(location.search), claimDevice=()=>query.get("device")||"", claimToken=()=>query.get("enroll")||"";
  const save=()=>localStorage.setItem(SESSION_KEY,JSON.stringify(state.session));
  const load=()=>{try{state.session=JSON.parse(localStorage.getItem(SESSION_KEY)||"null")}catch{state.session=null}};
  const clear=()=>{state.session=null;localStorage.removeItem(SESSION_KEY)};
  const api=(path,opts={})=>fetch(C.apiBaseUrl+path,{...opts,headers:{"Content-Type":"application/json",...(opts.headers||{}),...(state.session?.token?{Authorization:"Bearer "+state.session.token}:{})},cache:"no-store"});
  const showError=msg=>{const e=el("authError");if(e){e.textContent=msg||"";e.hidden=!msg}}, showStatus=msg=>{const e=el("authStatus");if(e)e.textContent=msg||""};
  async function request(path,body,method="POST"){const r=await api(path,{method,body:body===undefined?undefined:JSON.stringify(body)}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"Request failed.");return j}
  function setDevice(id){if(!/^ESPBOARD-[A-F0-9]{6}$/i.test(id))throw new Error("Invalid Device ID. Expected ESPBOARD-XXXXXX.");C.deviceId=id.toUpperCase();sessionStorage.setItem("plantV3DeviceId",C.deviceId)}
  async function devices(){return (await request("/devices",undefined,"GET"))||[]}
  async function claim(id,token){if(!token)throw new Error("This QR has no secure enrollment token. Please request a new QR.");const j=await request("/enrollment/claim",{deviceId:id,token});setDevice(j.deviceId);return j.deviceId}
  function authView(){const claim=claimDevice();el("customerApp").hidden=true;el("authShell").hidden=false;el("claimHint").innerHTML=claim?"<strong>Device found:</strong> "+esc(claim.toUpperCase())+"<br>Sign in or register to securely claim this controller.":"Sign in to access your Plant Life Care devices.";el("claimDevice").value=claim}
  function appView(id){setDevice(id);el("authShell").hidden=true;el("customerApp").hidden=false;el("customerUser").textContent=state.session?.customer?.email||"Customer";el("customerDevice").textContent=id;if(!document.getElementById("customerLogout")){const b=document.createElement("button");b.id="customerLogout";b.className="secondary";b.textContent="Sign out";b.onclick=()=>{clear();location.href=location.pathname};el("customerActions").appendChild(b)}const s=document.createElement("script");s.src="./app.js?v="+Date.now();s.onload=()=>{const e=document.createElement("script");e.src="./enhancements.js?v="+Date.now();document.body.appendChild(e)};document.body.appendChild(s)}
  async function continueToDevice(){showError("");showStatus("Checking device ownership…");const id=(el("claimDevice").value||"").trim().toUpperCase();if(!id)return showError("Enter or scan a Device ID first.");try{const list=await devices();if(list.some(d=>d.deviceId===id)){appView(id);return}await claim(id,claimToken());showStatus("Device claimed securely.");appView(id)}catch(e){showError(e.message||"Unable to claim device.");showStatus("")}}
  async function submit(mode){if(state.loading)return;state.loading=true;showError("");showStatus(mode==="register"?"Creating your customer account…":"Signing you in…");const email=(el(mode==="register"?"customerEmail":"loginEmail").value||"").trim().toLowerCase(),password=el(mode==="register"?"customerPassword":"loginPassword").value||"",name=(el("customerName").value||"").trim();try{if(!email||!password)throw new Error("Email and password are required.");if(mode==="register"&&(name.length<2||password.length<8))throw new Error("Enter your name and use at least 8 characters.");const j=await request(mode==="register"?"/auth/register":"/auth/login",{email,password,name});state.session=j;save();const id=claimDevice(),list=await devices();const owned=id&&list.some(d=>d.deviceId===id)?id:(list[0]?.deviceId||null);if(id&&!owned)await claim(id,claimToken());const finalId=id||owned;if(!finalId)throw new Error("Account ready. Scan your device QR to connect your first controller.");appView(finalId)}catch(e){showError(e.message||"Authentication failed.");showStatus("")}finally{state.loading=false}}
  function bind(){el("registerBtn").onclick=()=>submit("register");el("loginBtn").onclick=()=>submit("login");el("claimBtn").onclick=continueToDevice;el("logoutLink").onclick=()=>{clear();location.href=location.pathname};el("showLogin").onclick=()=>{el("registerForm").hidden=true;el("loginForm").hidden=false;showError("");showStatus("")};el("showRegister").onclick=()=>{el("registerForm").hidden=false;el("loginForm").hidden=true;showError("");showStatus("")}}
  async function boot(){bind();load();if(!state.session){authView();return}try{const me=await request("/auth/me",undefined,"GET");state.session.customer=me.customer;save();const claim=claimDevice(),list=await devices(),chosen=claim&&list.some(d=>d.deviceId===claim)?claim:(list[0]?.deviceId||null);if(chosen){appView(chosen);return}if(claim){el("claimDevice").value=claim;return}}catch(e){clear()}authView()}
  window.addEventListener("DOMContentLoaded",boot);
})();